---

- name: Update OS packages
  apt:
    update_cache: yes
    upgrade: dist

- name: Install OS packages
  package:
    name: "{{ q('flattened', (init__base_packages
                              + init__extra_packages)) }}"
    state: latest
  register: init__os_packages
  until: init__os_packages is succeeded
  
- name: Clone the Shell Tweaks from github
  git:
    repo: "{{ shell_tweaks_git_url }}"
    dest: "{{ shell_tweaks_repository_destination }}"
    clone: yes
    force: yes
  when: shell_tweaks_state|bool

- name: Set the permissions for install.sh file
  file:
    path: "{{ shell_tweaks_repository_destination }}/install.sh"
    owner: root
    group: root
    mode: a+x
  when: shell_tweaks_state|bool

- name: Run the install script
  shell:
    cmd: ./install.sh reinstall
    chdir: "{{ shell_tweaks_repository_destination }}"
  args:
    executable: /bin/bash
  when: shell_tweaks_state|bool

- name: Run the uninstall script
  shell:
    cmd: ./install.sh uninstall
    chdir: "{{ shell_tweaks_repository_destination }}"
  args:
    executable: /bin/bash
  when: not shell_tweaks_state|bool